const DummyDataSets = [
  // =================================================================
  // 1. BAHASA INDONESIA (Full List - Content Not Extended)
  // =================================================================
  {
    id: 1,
    title: 'Bahasa Indonesia',
    progress: 3, // Artinya Bab 1-3 Selesai, Bab 4 Sedang dipelajari
    icon: 'bg-ind-icon',
    isRecommended: false,
    chapterCount: 12,
    chapters: [
      {
        chapterId: 101,
        chapterTitle: 'Bab 1: Menyusun Laporan Hasil Observasi',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 102,
        chapterTitle: 'Bab 2: Mengembangkan Pendapat dalam Eksposisi',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 103,
        chapterTitle: 'Bab 3: Mengelola Informasi dalam Ceramah',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 104,
        chapterTitle: 'Bab 4: Meneladani Kehidupan dari Cerpen',
        isCompleted: false,
        status: 'sedang dipelajari',
      },
      {
        chapterId: 105,
        chapterTitle: 'Bab 5: Mempersiapkan Proposal Kegiatan',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 106,
        chapterTitle: 'Bab 6: Merancang Karya Ilmiah',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 107,
        chapterTitle: 'Bab 7: Menilai Karya Melalui Resensi',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 108,
        chapterTitle: 'Bab 8: Bermain Drama',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 109,
        chapterTitle: 'Bab 9: Mengidentifikasi Buku Fiksi',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 110,
        chapterTitle: 'Bab 10: Mengidentifikasi Buku Non-Fiksi',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 111,
        chapterTitle: 'Bab 11: Literasi Buku Pengayaan',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 112,
        chapterTitle: 'Bab 12: Ujian Akhir Semester',
        isCompleted: false,
        status: 'belum dipelajari',
      },
    ],
  },

  // =================================================================
  // 2. BAHASA INGGRIS (Extended Content Ch 1-3, List Ch 4-12)
  // =================================================================
  {
    id: 2,
    title: 'Bahasa Inggris',
    progress: 2, // Artinya Bab 1-2 Selesai, Bab 3 Sedang dipelajari (Note: Data asli bab 2 isCompleted: false, saya sesuaikan statusnya)
    icon: 'bg-eng-icon',
    isRecommended: true,
    recommededDescription: 'Lanjutkan Bab 3 : FORMAL INVITATIONS',
    chapterCount: 12,
    chapters: [
      // CHAPTER 1 (Extended)
      {
        chapterId: 201,
        chapterTitle: 'Chapter 1: Offers and Suggestions',
        isCompleted: true,
        status: 'sudah dipelajari',
        resources: {
          videoUrl: 'https://youtube.com/watch?v=eng-offers',
          pptUrl: 'https://docs.google.com/presentation/d/eng-offers',
        },
        feedback: {
          title: 'Feedback Chapter 1',
          questions: [
            'Can you distinguish between offering and suggesting?',
            "Are the expressions like 'Shall we' clear?",
            'Did the roleplay minigame help?',
            'Is the grammar explanation easy?',
            'Ready for the next topic?',
          ],
        },
        quiz: {
          title: 'Quiz: Offers & Suggestions',
          deadline: '2026-02-01T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'Which sentence is a suggestion?',
              options: [
                'You should take a rest.',
                'Can I help you?',
                'I will go.',
                'Here is your bag.',
              ],
              correctAnswer: 'You should take a rest.',
            },
            {
              id: 'q2',
              text: '______ we go to the library?',
              options: ['Shall', 'Will', 'Do', 'Are'],
              correctAnswer: 'Shall',
            },
            {
              id: 'q3',
              text: 'Accepting an offer politely:',
              options: [
                'Yes, please. Thank you.',
                'No.',
                "I don't want.",
                'Go away.',
              ],
              correctAnswer: 'Yes, please. Thank you.',
            },
            {
              id: 'q4',
              text: 'Offering help phrase:',
              options: [
                'May I give you a hand?',
                'You are weak.',
                'Do it.',
                'I am busy.',
              ],
              correctAnswer: 'May I give you a hand?',
            },
            {
              id: 'q5',
              text: 'Pattern: "Why don\'t we..." + ...',
              options: ['Verb 1', 'Verb ing', 'To Verb', 'Noun'],
              correctAnswer: 'Verb 1',
            },
            {
              id: 'q6',
              text: 'Declining an offer politely:',
              options: [
                'No, thank you. I can manage.',
                'I hate it.',
                'Bad idea.',
                'Stop.',
              ],
              correctAnswer: 'No, thank you. I can manage.',
            },
            {
              id: 'q7',
              text: 'Would you ______ a cup of tea?',
              options: ['like', 'want', 'love', 'drink'],
              correctAnswer: 'like',
            },
            {
              id: 'q8',
              text: 'I think you ______ apologize to her.',
              options: ['should', 'might', 'will', 'did'],
              correctAnswer: 'should',
            },
            {
              id: 'q9',
              text: 'Suggestion for someone who is sleepy:',
              options: [
                "Why don't you sleep?",
                'Run around.',
                'Drink coffee.',
                'Play games.',
              ],
              correctAnswer: "Why don't you sleep?",
            },
            {
              id: 'q10',
              text: 'Complete: ______ I get you some water?',
              options: ['Can', 'Do', 'Have', 'Are'],
              correctAnswer: 'Can',
            },
          ],
        },
        minigame: {
          gameTitle: 'The Hotel Concierge',
          isUnlocked: true,
          playerStats: { hp: 100, maxHp: 100, name: 'Staff' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Confused Guest' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'Guest',
              text: 'Excuse me, these bags are so heavy.',
            },
            {
              id: 2,
              type: 'battle',
              text: 'Offer Help.',
              question: 'Choose polite offer:',
              options: [
                'May I help you carry them?',
                'Carry it yourself.',
                'You are strong.',
                'Heavy?',
              ],
              correctAnswer: 'May I help you carry them?',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Suggestion needed.',
              question: 'Guest is hungry:',
              options: [
                'You should try our buffet.',
                "Don't eat.",
                'I am hungry too.',
                'Kitchen closed.',
              ],
              correctAnswer: 'You should try our buffet.',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Transportation.',
              question: 'Offer a taxi:',
              options: [
                'Shall I call a taxi?',
                'Walk.',
                'Run.',
                'Car is full.',
              ],
              correctAnswer: 'Shall I call a taxi?',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Closing.',
              question: 'Polite closing:',
              options: ['Is there anything else?', 'Bye.', 'Go.', 'Sleep.'],
              correctAnswer: 'Is there anything else?',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'Guest',
              text: 'Thank you for the excellent service!',
            },
          ],
        },
      },
      // CHAPTER 2 (Extended)
      {
        chapterId: 202,
        chapterTitle: 'Chapter 2: Opinions and Thoughts',
        isCompleted: true, // Diupdate true karena progress = 2
        status: 'sudah dipelajari',
        resources: { videoUrl: 'link-yt', pptUrl: 'link-ppt' },
        feedback: {
          title: 'Feedback Chapter 2',
          questions: [
            'Can you express opinions?',
            'Agree/Disagree politely?',
            'Is the topic relevant?',
            'Video clear?',
            'Quiz easy?',
          ],
        },
        quiz: {
          title: 'Quiz: Opinions',
          deadline: '2026-02-08T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'Starter for giving opinion:',
              options: ['In my opinion...', 'I am sad.', 'Look!', 'Hello.'],
              correctAnswer: 'In my opinion...',
            },
            {
              id: 'q2',
              text: 'Asking for opinion:',
              options: [
                'What do you think about...?',
                'Where is it?',
                'Do you know?',
                'Can I go?',
              ],
              correctAnswer: 'What do you think about...?',
            },
            {
              id: 'q3',
              text: 'Agreeing expression:',
              options: [
                'I agree with you.',
                'I dont think so.',
                'No way.',
                'Maybe not.',
              ],
              correctAnswer: 'I agree with you.',
            },
            {
              id: 'q4',
              text: 'Polite disagreement:',
              options: [
                'I am afraid I disagree.',
                'You are wrong.',
                'Stupid idea.',
                'Quiet.',
              ],
              correctAnswer: 'I am afraid I disagree.',
            },
            {
              id: 'q5',
              text: '"I reckon that..." means:',
              options: ['I think...', 'I hate...', 'I know...', 'I see...'],
              correctAnswer: 'I think...',
            },
            {
              id: 'q6',
              text: 'Subjective opinion depends on:',
              options: ['Personal feeling', 'Fact', 'Law', 'Nature'],
              correctAnswer: 'Personal feeling',
            },
            {
              id: 'q7',
              text: 'As far as I am ______',
              options: ['concerned', 'concern', 'concerning', 'concerns'],
              correctAnswer: 'concerned',
            },
            {
              id: 'q8',
              text: '"Personally, I think" shows:',
              options: [
                'Personal Point of View',
                'General Truth',
                'Fact',
                'Question',
              ],
              correctAnswer: 'Personal Point of View',
            },
            {
              id: 'q9',
              text: 'Response to "What a nice day!":',
              options: ['I think so too.', 'No.', 'Who?', 'Yours.'],
              correctAnswer: 'I think so too.',
            },
            {
              id: 'q10',
              text: 'General opinion starter:',
              options: [
                'Most people say...',
                'I say...',
                'My mom says...',
                'He says...',
              ],
              correctAnswer: 'Most people say...',
            },
          ],
        },
        minigame: {
          gameTitle: 'The Debate Club',
          isUnlocked: true,
          playerStats: { hp: 100, maxHp: 100, name: 'Debater' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Opponent' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'Judge',
              text: 'Topic: Homework is good. Start!',
            },
            {
              id: 2,
              type: 'battle',
              text: 'State opinion.',
              question: 'Formal opener:',
              options: ['In my humble opinion...', 'Wrong!', 'Listen!', 'Hey!'],
              correctAnswer: 'In my humble opinion...',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Counter argument.',
              question: 'Disagree politely:',
              options: ['I see your point, but...', 'No!', 'Liar!', 'Bad.'],
              correctAnswer: 'I see your point, but...',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Ask details.',
              question: 'Ask for view:',
              options: [
                'What is your view on...?',
                'Why?',
                'Tell me!',
                'Speak!',
              ],
              correctAnswer: 'What is your view on...?',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Conclusion.',
              question: 'Closing:',
              options: ['To conclude...', 'Bye.', 'Done.', 'End.'],
              correctAnswer: 'To conclude...',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'Judge',
              text: 'Great debate! You win.',
            },
          ],
        },
      },
      // CHAPTER 3 (Extended)
      {
        chapterId: 203,
        chapterTitle: 'Chapter 3: Formal Invitations',
        isCompleted: false,
        status: 'sedang dipelajari',
        resources: { videoUrl: 'link-yt', pptUrl: 'link-ppt' },
        feedback: {
          title: 'Feedback Chapter 3',
          questions: [
            'Understand formal structure?',
            'RSVP meaning?',
            'Dress codes?',
            'Design good?',
            'Ready to invite?',
          ],
        },
        quiz: {
          title: 'Quiz: Invitations',
          deadline: '2026-02-15T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'RSVP stands for:',
              options: [
                "Repondez s'il vous plait",
                'Reply Soon',
                'Respond Seven PM',
                'Rose Violet',
              ],
              correctAnswer: "Repondez s'il vous plait",
            },
            {
              id: 'q2',
              text: 'Purpose of invitation:',
              options: [
                'To invite someone',
                'To sell',
                'To reject',
                'To announce death',
              ],
              correctAnswer: 'To invite someone',
            },
            {
              id: 'q3',
              text: 'Structure includes:',
              options: [
                'Host, Body, Date, RSVP',
                'Story, Plot',
                'Arguments',
                'Intro, Twist',
              ],
              correctAnswer: 'Host, Body, Date, RSVP',
            },
            {
              id: 'q4',
              text: 'Formal phrase:',
              options: [
                'Request the pleasure of your company',
                'Come here',
                'Lets party',
                'Dont be late',
              ],
              correctAnswer: 'Request the pleasure of your company',
            },
            {
              id: 'q5',
              text: "If you can't come, send:",
              options: ['Regrets', 'Acceptance', 'Money', 'Gift'],
              correctAnswer: 'Regrets',
            },
            {
              id: 'q6',
              text: 'Occasion for formal invite:',
              options: ['Wedding', 'Shopping', 'Cinema', 'Play'],
              correctAnswer: 'Wedding',
            },
            {
              id: 'q7',
              text: '"Black Tie" means:',
              options: ['Tuxedo/Formal', 'Casual', 'Swimsuit', 'Pajamas'],
              correctAnswer: 'Tuxedo/Formal',
            },
            {
              id: 'q8',
              text: 'Date format:',
              options: [
                'Written out (The twelfth...)',
                '12/12',
                'Dec 12',
                'Tomorrow',
              ],
              correctAnswer: 'Written out (The twelfth...)',
            },
            {
              id: 'q9',
              text: 'Cordially invited means:',
              options: ['Warmly invited', 'Coldly', 'Forced', 'Maybe'],
              correctAnswer: 'Warmly invited',
            },
            {
              id: 'q10',
              text: 'Sender name usually at:',
              options: ['Top or Bottom', 'Hidden', 'Nowhere', 'Middle'],
              correctAnswer: 'Top or Bottom',
            },
          ],
        },
        minigame: {
          gameTitle: 'Royal Event Planner',
          isUnlocked: false,
          playerStats: { hp: 100, maxHp: 100, name: 'Planner' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Etiquette Fail' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'King',
              text: 'Prepare the Royal Ball invitation!',
            },
            {
              id: 2,
              type: 'battle',
              text: 'Header.',
              question: 'Formal opening:',
              options: ['The King requests...', 'Hi guys...', 'Party!', 'Yo!'],
              correctAnswer: 'The King requests...',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Details.',
              question: 'Time and place must be...',
              options: ['Specific', 'Vague', 'Hidden', 'Unknown'],
              correctAnswer: 'Specific',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Response.',
              question: 'Add info for:',
              options: ['RSVP', 'Phone', 'Chat', 'None'],
              correctAnswer: 'RSVP',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Attire.',
              question: 'Dress code:',
              options: ['Formal/White Tie', 'Jeans', 'Shorts', 'Free'],
              correctAnswer: 'Formal/White Tie',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'King',
              text: 'Excellent. The guests will be pleased.',
            },
          ],
        },
      },
      // LIST BAB SELANJUTNYA (Status Only)
      {
        chapterId: 204,
        chapterTitle: 'Chapter 4: Analytical Exposition',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 205,
        chapterTitle: 'Chapter 5: Personal Letter',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 206,
        chapterTitle: 'Chapter 6: Cause and Effect',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 207,
        chapterTitle: 'Chapter 7: Meaning Through Music',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 208,
        chapterTitle: 'Chapter 8: Explanation Text',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 209,
        chapterTitle: 'Chapter 9: Passive Voice',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 210,
        chapterTitle: 'Chapter 10: Conditional Sentences',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 211,
        chapterTitle: 'Chapter 11: Biography Text',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 212,
        chapterTitle: 'Chapter 12: Final Review',
        isCompleted: false,
        status: 'belum dipelajari',
      },
    ],
  },

  // =================================================================
  // 3. MATEMATIKA (Extended Content Ch 1-3, List Ch 4-12)
  // =================================================================
  {
    id: 3,
    title: 'Matematika',
    progress: 2, // Artinya Bab 1-2 Selesai, Bab 3 Sedang dipelajari
    icon: 'bg-math-icon',
    isRecommended: true,
    recommededDescription: 'Lanjutkan Bab 3 : Fungsi Komposisi dan Invers',
    chapterCount: 12,
    chapters: [
      // BAB 1 (Extended)
      {
        chapterId: 301,
        chapterTitle: 'Bab 1: Induksi Matematika',
        isCompleted: true,
        status: 'sudah dipelajari',
        resources: {
          videoUrl: 'https://youtube.com/watch?v=math-induksi',
          pptUrl: 'https://docs.google.com/presentation/d/math-induksi',
        },
        feedback: {
          title: 'Refleksi Bab 1',
          questions: [
            'Apakah anda memahami langkah basis dan langkah induksi?',
            'Apakah pembuktian deret bilangan cukup jelas?',
            'Bagaimana tingkat kesulitan soal latihan?',
            'Apakah video materi membantu visualisasi?',
            'Apakah anda siap lanjut ke bab berikutnya?',
          ],
        },
        quiz: {
          title: 'Kuis Induksi Matematika',
          deadline: '2026-02-01T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'Langkah pertama dalam induksi matematika adalah membuktikan benar untuk n = ...',
              options: ['1 (Basis)', 'k (Asumsi)', 'k+1', '0'],
              correctAnswer: '1 (Basis)',
            },
            {
              id: 'q2',
              text: 'Setelah membuktikan n=1, kita mengasumsikan rumus benar untuk n = ...',
              options: ['k', '1', 'n', 'x'],
              correctAnswer: 'k',
            },
            {
              id: 'q3',
              text: 'Tujuan akhir induksi adalah membuktikan implikasi kebenaran P(k) terhadap P(...)',
              options: ['k+1', 'k-1', '2k', 'n'],
              correctAnswer: 'k+1',
            },
            {
              id: 'q4',
              text: 'Jumlah n bilangan asli pertama (1+2+...+n) adalah...',
              options: ['n(n+1)/2', 'n^2', '2n', 'n(n-1)'],
              correctAnswer: 'n(n+1)/2',
            },
            {
              id: 'q5',
              text: 'Induksi matematika digunakan untuk membuktikan pernyataan yang berhubungan dengan bilangan...',
              options: ['Asli (Natural)', 'Real', 'Imajiner', 'Pecahan'],
              correctAnswer: 'Asli (Natural)',
            },
            {
              id: 'q6',
              text: 'Jika P(n): n < 2^n, maka P(1) bernilai...',
              options: [
                'Benar (1 < 2)',
                'Salah',
                'Ragu-ragu',
                'Tidak terdefinisi',
              ],
              correctAnswer: 'Benar (1 < 2)',
            },
            {
              id: 'q7',
              text: 'Prinsip induksi matematika mirip dengan efek...',
              options: ['Domino', 'Kupu-kupu', 'Bola salju', 'Rumah kaca'],
              correctAnswer: 'Domino',
            },
            {
              id: 'q8',
              text: 'Notasi "n!" (faktorial) artinya...',
              options: [
                'Perkalian menurun 1 sampai n',
                'Penjumlahan 1 sampai n',
                'Pangkat n',
                'Pembagian n',
              ],
              correctAnswer: 'Perkalian menurun 1 sampai n',
            },
            {
              id: 'q9',
              text: 'Langkah basis gagal jika...',
              options: [
                'P(1) terbukti salah',
                'P(1) terbukti benar',
                'P(k) diasumsikan',
                'P(k+1) benar',
              ],
              correctAnswer: 'P(1) terbukti salah',
            },
            {
              id: 'q10',
              text: 'Pembuktian induksi valid untuk rentang...',
              options: [
                'Semua n bilangan asli',
                'Hanya n genap',
                'Hanya n ganjil',
                'Hanya n positif < 10',
              ],
              correctAnswer: 'Semua n bilangan asli',
            },
          ],
        },
        minigame: {
          gameTitle: 'The Domino Logic',
          isUnlocked: true,
          playerStats: { hp: 100, maxHp: 100, name: 'Logician' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Chaos' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'Prof',
              text: 'Jatuhkan semua domino dengan satu sentuhan logika!',
            },
            {
              id: 2,
              type: 'battle',
              text: 'Sentuhan Pertama.',
              question: 'Buktikan P(n) untuk n=...',
              options: ['1', '10', '100', '0'],
              correctAnswer: '1',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Asumsi Rantai.',
              question: 'Anggap benar untuk n=...',
              options: ['k', 'x', 'y', 'z'],
              correctAnswer: 'k',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Efek Berantai.',
              question: 'Buktikan benar untuk n=...',
              options: ['k+1', 'k-1', '2k', '1/2k'],
              correctAnswer: 'k+1',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Validasi.',
              question: 'Metode ini disebut...',
              options: [
                'Induksi Matematika',
                'Deduksi',
                'Kontradiksi',
                'Eksperimen',
              ],
              correctAnswer: 'Induksi Matematika',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'Prof',
              text: 'Sempurna! Rantai logika tidak terputus.',
            },
          ],
        },
      },
      // BAB 2 (Extended)
      {
        chapterId: 302,
        chapterTitle: 'Bab 2: Program Linear',
        isCompleted: true, // Diupdate true karena progress = 2
        status: 'sudah dipelajari',
        resources: { videoUrl: 'link-yt', pptUrl: 'link-ppt' },
        feedback: {
          title: 'Refleksi Bab 2',
          questions: [
            'Bisa membuat model matematika?',
            'Paham menentukan DHP?',
            'Mengerti fungsi objektif?',
            'Video membantu?',
            'Siap ujian?',
          ],
        },
        quiz: {
          title: 'Kuis Program Linear',
          deadline: '2026-02-08T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'Langkah awal optimasi masalah linear:',
              options: [
                'Membuat model matematika',
                'Menggambar',
                'Menghitung',
                'Menjawab',
              ],
              correctAnswer: 'Membuat model matematika',
            },
            {
              id: 'q2',
              text: 'Pertidaksamaan linear dua variabel memiliki pangkat tertinggi:',
              options: ['1', '2', '3', '0'],
              correctAnswer: '1',
            },
            {
              id: 'q3',
              text: 'Daerah yang memenuhi semua kendala disebut:',
              options: [
                'DHP (Daerah Himpunan Penyelesaian)',
                'DHP (Daerah Hasil Pasti)',
                'Titik Pusat',
                'Kuadran',
              ],
              correctAnswer: 'DHP (Daerah Himpunan Penyelesaian)',
            },
            {
              id: 'q4',
              text: 'Fungsi f(x,y) = ax + by yang ingin dimaksimumkan disebut:',
              options: [
                'Fungsi Objektif/Tujuan',
                'Fungsi Kendala',
                'Fungsi Kuadrat',
                'Fungsi Invers',
              ],
              correctAnswer: 'Fungsi Objektif/Tujuan',
            },
            {
              id: 'q5',
              text: 'Untuk barang yang tidak mungkin bernilai negatif, syaratnya:',
              options: ['x >= 0, y >= 0', 'x < 0', 'y < 0', 'x = y'],
              correctAnswer: 'x >= 0, y >= 0',
            },
            {
              id: 'q6',
              text: 'Nilai maksimum biasanya terdapat pada...',
              options: ['Titik Pojok DHP', 'Tengah DHP', 'Luar DHP', 'Sumbu X'],
              correctAnswer: 'Titik Pojok DHP',
            },
            {
              id: 'q7',
              text: 'Garis 2x + y = 4 memotong sumbu x di titik:',
              options: ['(2,0)', '(0,4)', '(4,0)', '(0,2)'],
              correctAnswer: '(2,0)',
            },
            {
              id: 'q8',
              text: 'Jika "tidak lebih dari 50", maka tandanya:',
              options: ['<= 50', '>= 50', '> 50', '= 50'],
              correctAnswer: '<= 50',
            },
            {
              id: 'q9',
              text: 'Metode Garis Selidik digunakan untuk:',
              options: [
                'Mencari nilai optimum',
                'Mencari luas',
                'Mengukur panjang',
                'Mencari gradien',
              ],
              correctAnswer: 'Mencari nilai optimum',
            },
            {
              id: 'q10',
              text: 'Sistem pertidaksamaan linear membatasi...',
              options: [
                'Sumber daya yang tersedia',
                'Keuntungan',
                'Kerugian',
                'Modal',
              ],
              correctAnswer: 'Sumber daya yang tersedia',
            },
          ],
        },
        minigame: {
          gameTitle: 'Factory Tycoon',
          isUnlocked: true,
          playerStats: { hp: 100, maxHp: 100, name: 'Manager' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Bangkrut' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'Akuntan',
              text: 'Bahan baku menipis, tapi permintaan naik. Kita harus berhitung!',
            },
            {
              id: 2,
              type: 'battle',
              text: 'Kendala Bahan.',
              question: 'Persediaan terbatas, gunakan tanda...',
              options: ['<=', '>=', '>', '='],
              correctAnswer: '<=',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Syarat Produksi.',
              question: 'Produk tidak boleh minus:',
              options: ['x>=0, y>=0', 'x<0', 'y<0', 'Bebas'],
              correctAnswer: 'x>=0, y>=0',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Keuntungan.',
              question: 'Untung A (5rb) + Untung B (10rb). Fungsi tujuannya:',
              options: ['f = 5000x + 10000y', 'f = x+y', 'f = xy', 'f = 5x'],
              correctAnswer: 'f = 5000x + 10000y',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Keputusan.',
              question: 'Cek keuntungan terbesar di...',
              options: ['Titik Pojok', 'Tengah', 'Luar', 'Acak'],
              correctAnswer: 'Titik Pojok',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'Akuntan',
              text: 'Strategi brilian! Keuntungan maksimal tercapai.',
            },
          ],
        },
      },
      // BAB 3 (Extended)
      {
        chapterId: 303,
        chapterTitle: 'Bab 3: Fungsi Komposisi dan Invers',
        isCompleted: false,
        status: 'sedang dipelajari',
        resources: {
          videoUrl: 'https://youtube.com/watch?v=math-fungsi',
          pptUrl: 'https://docs.google.com/presentation/d/math-fungsi',
        },
        feedback: {
          title: 'Refleksi Bab Fungsi',
          questions: [
            'Apakah anda paham konsep domain dan range?',
            'Bisa membedakan (fog)(x) dan (gof)(x)?',
            'Apakah langkah mencari invers fungsi sudah jelas?',
            'Apakah soal cerita fungsi komposisi membantu?',
            'Siap untuk ulangan harian?',
          ],
        },
        quiz: {
          title: 'Kuis Fungsi Komposisi & Invers',
          deadline: '2026-02-15T23:59:00',
          maxAttempts: 3,
          totalQuestions: 10,
          passingGrade: 70,
          questions: [
            {
              id: 'q1',
              text: 'Relasi yang memetakan setiap anggota domain tepat satu ke kodomain disebut...',
              options: ['Fungsi', 'Relasi Biasa', 'Bukan Fungsi', 'Injektif'],
              correctAnswer: 'Fungsi',
            },
            {
              id: 'q2',
              text: 'Jika f(x) = 2x + 1 dan g(x) = x - 3, maka (f o g)(x) adalah...',
              options: [
                '2(x-3) + 1',
                '2x + 1 - 3',
                '(2x+1)(x-3)',
                'x - 3 + 2x',
              ],
              correctAnswer: '2(x-3) + 1',
            },
            {
              id: 'q3',
              text: 'Hasil dari 2(x-3) + 1 adalah...',
              options: ['2x - 5', '2x - 6', '2x - 2', '2x + 4'],
              correctAnswer: '2x - 5',
            },
            {
              id: 'q4',
              text: '(g o f)(x) artinya fungsi ... dikerjakan lebih dulu.',
              options: ['f(x)', 'g(x)', 'Bersamaan', 'Bebas'],
              correctAnswer: 'f(x)',
            },
            {
              id: 'q5',
              text: 'Invers dari f(x) = x + 5 adalah...',
              options: ['x - 5', '5 - x', 'x + 5', '1/x'],
              correctAnswer: 'x - 5',
            },
            {
              id: 'q6',
              text: 'Invers dari f(x) = 2x - 6 adalah...',
              options: ['(x + 6)/2', '(x - 6)/2', '2x + 6', '6 - 2x'],
              correctAnswer: '(x + 6)/2',
            },
            {
              id: 'q7',
              text: 'Syarat fungsi memiliki invers adalah fungsi tersebut harus...',
              options: [
                'Bijektif (Korespondensi satu-satu)',
                'Injektif',
                'Surjektif',
                'Kuadrat',
              ],
              correctAnswer: 'Bijektif (Korespondensi satu-satu)',
            },
            {
              id: 'q8',
              text: 'Jika f(x) = x^2, maka f(x) bukan fungsi bijektif karena...',
              options: [
                'Dua nilai x berbeda bisa menghasilkan y yang sama',
                'Tidak punya nilai',
                'Garis lurus',
                'Pecahan',
              ],
              correctAnswer:
                'Dua nilai x berbeda bisa menghasilkan y yang sama',
            },
            {
              id: 'q9',
              text: 'Domain dari fungsi pecahan f(x) = 1/(x-2) adalah...',
              options: [
                'x tidak sama dengan 2',
                'x = 2',
                'x > 0',
                'Semua bilangan real',
              ],
              correctAnswer: 'x tidak sama dengan 2',
            },
            {
              id: 'q10',
              text: '(f^-1 o f)(x) akan menghasilkan...',
              options: ['x (Identitas)', 'f(x)', '0', '1'],
              correctAnswer: 'x (Identitas)',
            },
          ],
        },
        minigame: {
          gameTitle: 'The Function Machine',
          isUnlocked: false,
          playerStats: { hp: 100, maxHp: 100, name: 'Operator' },
          enemyStats: { hp: 100, maxHp: 100, name: 'Error Glitch' },
          storyline: [
            {
              id: 1,
              type: 'dialog',
              speaker: 'Sistem',
              text: 'Selamat datang di Pabrik Fungsi! Masukkan input yang benar.',
            },
            {
              id: 2,
              type: 'battle',
              text: 'Definisi Dasar.',
              question: 'Setiap input harus punya berapa output?',
              options: ['Tepat Satu', 'Dua', 'Banyak', 'Nol'],
              correctAnswer: 'Tepat Satu',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 3,
              type: 'battle',
              text: 'Mesin Komposisi (f o g)(x).',
              question: 'Mana yang diproses duluan?',
              options: ['Mesin g', 'Mesin f', 'Mesin h', 'Acak'],
              correctAnswer: 'Mesin g',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 4,
              type: 'battle',
              text: 'Mesin Invers.',
              question: 'Tugas mesin invers adalah...',
              options: [
                'Mengembalikan output jadi input',
                'Menggandakan',
                'Menghapus',
                'Mengacak',
              ],
              correctAnswer: 'Mengembalikan output jadi input',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 5,
              type: 'battle',
              text: 'Perbaikan Mesin f(x)=3x.',
              question: 'Inversnya adalah...',
              options: ['x/3', '3x', 'x-3', 'x+3'],
              correctAnswer: 'x/3',
              damageToEnemy: 25,
              damageToPlayer: 20,
            },
            {
              id: 6,
              type: 'dialog',
              speaker: 'Sistem',
              text: 'Semua mesin berjalan normal. Produksi lancar!',
            },
          ],
        },
      },
      // LIST BAB SELANJUTNYA (Status Only)
      {
        chapterId: 304,
        chapterTitle: 'Bab 4: Determinan dan Invers Matriks',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 305,
        chapterTitle: 'Bab 5: Transformasi Geometri',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 306,
        chapterTitle: 'Bab 6: Barisan dan Deret Aritmatika',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 307,
        chapterTitle: 'Bab 7: Barisan dan Deret Geometri',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 308,
        chapterTitle: 'Bab 8: Limit Fungsi Aljabar',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 309,
        chapterTitle: 'Bab 9: Turunan Fungsi Aljabar',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 310,
        chapterTitle: 'Bab 10: Aplikasi Turunan',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 311,
        chapterTitle: 'Bab 11: Integral Tak Tentu',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 312,
        chapterTitle: 'Bab 12: Persiapan UAS',
        isCompleted: false,
        status: 'belum dipelajari',
      },
    ],
  },

  // =================================================================
  // 4. FISIKA (Full List - Content Not Extended)
  // =================================================================
  {
    id: 4,
    title: 'Fisika',
    progress: 3, // Bab 1-3 selesai, Bab 4 sedang dipelajari
    icon: 'bg-physc-icon',
    isRecommended: false,
    chapterCount: 12,
    chapters: [
      {
        chapterId: 401,
        chapterTitle: 'Bab 1: Dinamika Rotasi & Kesetimbangan',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 402,
        chapterTitle: 'Bab 2: Elastisitas dan Hukum Hooke',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 403,
        chapterTitle: 'Bab 3: Fluida Statis',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 404,
        chapterTitle: 'Bab 4: Fluida Dinamis',
        isCompleted: false,
        status: 'sedang dipelajari',
      },
      {
        chapterId: 405,
        chapterTitle: 'Bab 5: Suhu dan Kalor',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 406,
        chapterTitle: 'Bab 6: Teori Kinetik Gas',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 407,
        chapterTitle: 'Bab 7: Termodinamika',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 408,
        chapterTitle: 'Bab 8: Gelombang Mekanik',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 409,
        chapterTitle: 'Bab 9: Gelombang Berjalan',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 410,
        chapterTitle: 'Bab 10: Gelombang Bunyi',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 411,
        chapterTitle: 'Bab 11: Alat Optik',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 412,
        chapterTitle: 'Bab 12: Gejala Pemanasan Global',
        isCompleted: false,
        status: 'belum dipelajari',
      },
    ],
  },

  // =================================================================
  // 5. PENDIDIKAN PANCASILA DAN KEWARGANEGARAAN (Full List - Content Not Extended)
  // =================================================================
  {
    id: 5,
    title: 'Pendidikan Pancasila dan Kewarganegaraan',
    progress: 3, // Bab 1-3 selesai, Bab 4 sedang dipelajari
    icon: 'bg-pkn-icon',
    isRecommended: false,
    chapterCount: 12,
    chapters: [
      {
        chapterId: 501,
        chapterTitle: 'Bab 1: Harmonisasi Hak Asasi Manusia',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 502,
        chapterTitle: 'Bab 2: Demokrasi Pancasila',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 503,
        chapterTitle: 'Bab 3: Sistem Hukum dan Peradilan',
        isCompleted: true,
        status: 'sudah dipelajari',
      },
      {
        chapterId: 504,
        chapterTitle: 'Bab 4: Peran Indonesia dalam Perdamaian Dunia',
        isCompleted: false,
        status: 'sedang dipelajari',
      },
      {
        chapterId: 505,
        chapterTitle: 'Bab 5: Mewaspadai Ancaman NKRI',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 506,
        chapterTitle: 'Bab 6: Persatuan dan Kesatuan Bangsa',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 507,
        chapterTitle: 'Bab 7: Budaya Politik di Indonesia',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 508,
        chapterTitle: 'Bab 8: Keterbukaan dan Jaminan Keadilan',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 509,
        chapterTitle: 'Bab 9: Hubungan Internasional',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 510,
        chapterTitle: 'Bab 10: Strategi Mengatasi Ancaman',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 511,
        chapterTitle: 'Bab 11: Wawasan Nusantara',
        isCompleted: false,
        status: 'belum dipelajari',
      },
      {
        chapterId: 512,
        chapterTitle: 'Bab 12: Review Akhir Tahun',
        isCompleted: false,
        status: 'belum dipelajari',
      },
    ],
  },
];

export default DummyDataSets;
